with Ada.Text_IO; use Ada.Text_IO;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Float_Text_IO; use Ada.Float_Text_IO;


procedure adao11 is
   
   Heltal : Integer;
   Flyttal : Float;
   Tecken : Character;
   Text : String(1..5);
   
begin
   Put("Skriv in ett heltal: ");
   Get(Heltal);
   Put("Du skrev in talet: ");
   Put(Heltal, Width=>2);
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in fem heltal: ");
   Get(Heltal);
   Put("Du skrev in talen: ");
   Put(Heltal, Width=>1);
   Put(" ");
   Get(Heltal);
   Put(Heltal, Width=>1);
   Put(" ");
   Get(Heltal);
   Put(Heltal, Width=>1);
   Put(" ");
   Get(Heltal);
   Put(Heltal, Width=>1);
   Put(" ");
   Get(Heltal);
   Put(Heltal, Width=>1);
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in ett flyttal: ");
   Get(Flyttal);
   Put("Du skrev in flyttalet: ");
   Put(Flyttal, Fore=>1, Aft=>3, Exp=>0);
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in ett heltal och ett flyttal: ");
   Get(Heltal);
   Get(Flyttal);
   Put("Du skrev in heltalet: ");
   Put(Heltal, Width=>9);
   New_Line;
   Put("Du skrev in flyttalet:");
   Put(Flyttal, Fore=>4, Aft=>4, Exp=>0);
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in ett tecken: ");
   Get(Tecken);
   Put("Du skrev in tecknet: ");
   Put(Tecken);
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in en sträng med 5 tecken: ");
   Get(Text(1..5));
   Put("Du skrev in strängen: ");
   Put(Text(1..5));  
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in en sträng med 3 tecken: ");
   Get(Text(1..3));
   Put("Du skrev in strängen: ");
   Put(Text(1..3));
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in ett heltal och en sträng med 5 tecken: ");
   Get(Heltal);
       loop
        Get (Tecken);
        exit when Tecken = ' ' or Tecken = '.';
    end loop;
   Get(Text);
   Put("Du skrev in talet |");
   Put(Heltal, Width=>1);
   Put("| och strängen |");
   Put(Text(1..5)); --Put(Text(2..6));
   Put("|.");  
   Skip_Line;
   New_Line;
   New_Line;
   Put("Skriv in en sträng med 3 tecken och ett flyttal: ");
   Get(Text(1..3));
   Get(Flyttal);
   Put("Du skrev in """);
   Put(Flyttal, Fore=>2, Aft=>3, Exp=>0);
   Put(""" och """); 
   Put(Text(1..3));
   Put(""".");   
   Skip_Line;
   New_Line;
   New_Line;
   
   Put("Skriv in en sträng som är maximalt 5 tecken: ");
   Get_Line(Text, Last=>Heltal);
   Put("Du skrev in strängen: ");
   Put_Line(Text(1..Heltal));
   if Heltal >= 5 then
     Skip_Line;
     New_Line;
     Put("Skriv in en sträng som är maximalt 5 tecken: ");
     Get_Line(Text, Last=>Heltal);
     Put("Du skrev in strängen: ");
     Put_Line(Text(1..Heltal));
   elsif  Heltal < 5 then 
       New_Line;
       Put("Skriv in en sträng som är maximalt 5 tecken: ");
       Get_Line(Text, Last=>Heltal);
       Put("Du skrev in strängen: ");
       Put_Line(Text(1..Heltal));
     end if;
   New_Line;
end adao11;
